blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question
    url: https://github.com/gautamsuneja/ai-design-system-gen/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/gautamsuneja/ai-design-system-gen/blob/main/README.md
    about: Read the documentation and setup guides
  - name: 🔒 Report a Security Vulnerability
    url: https://github.com/gautamsuneja/ai-design-system-gen/blob/main/SECURITY.md
    about: Report security issues privately
